CREATE SCHEMA IF NOT EXISTS MECJ_FINANCE;

USE MECJ_FINANCE;

CREATE TABLE IF NOT EXISTS USER (
	Userid INT NOT NULL AUTO_INCREMENT,
	Name VARCHAR(128) NOT NULL,
	DOB TIMESTAMP NOT NULL,
	CONSTRAINT User_PK PRIMARY KEY (Userid)
);

CREATE TABLE IF NOT EXISTS GOAL (
	UserId INT NOT NULL,
	Goalid INT NOT NULL AUTO_INCREMENT,
	Totalamount FLOAT NOT NULL,
	Currentamount FLOAT NOT NULL,
	Description VARCHAR(128) NOT NULL,
	CONSTRAINT Goal_PK PRIMARY KEY (Goalid, UserId)
);

CREATE TABLE IF NOT EXISTS CATEGORY (
    UserId INT NOT NULL,
	Categoryid INT NOT NULL AUTO_INCREMENT,
	Description VARCHAR(128) NOT NULL,
	Title VARCHAR(128) NOT NULL,
	CONSTRAINT Category_PK PRIMARY KEY (Categoryid, UserId)
);

CREATE TABLE IF NOT EXISTS EXPENSE (
	UserId INT NOT NULL,
	Expenseid INT NOT NULL AUTO_INCREMENT,
	Title VARCHAR(128) NOT NULL,
	Description VARCHAR(128) NOT NULL,
	Amount FLOAT NOT NULL,
	Category INT NOT NULL,
	CONSTRAINT Expense_PK PRIMARY KEY (Expenseid, UserId)
);

CREATE TABLE IF NOT EXISTS BILL (
	Billid INT NOT NULL,
	Recurringtime VARCHAR(128) NOT NULL,
	Duedate TIMESTAMP NOT NULL,
	CONSTRAINT Bill_PK PRIMARY KEY (Billid)
);

CREATE TABLE IF NOT EXISTS TRANSACTION (
	Transactionid INT NOT NULL,
	Date TIMESTAMP NOT NULL,
	CONSTRAINT Transaction_PK PRIMARY KEY (Transactionid)
);

CREATE TABLE IF NOT EXISTS BUDGET (
	UserId INT NOT NULL,
	BudgetId INT NOT NULL,
	Description VARCHAR(128),
	PRIMARY KEY (UserId, BudgetId)
);